// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartPPC.Api.Data;

#nullable disable

namespace SmartPPC.Api.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251206015034_FixStationIdTypes")]
    partial class FixStationIdTypes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.Configuration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "IsActive");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.GeneralSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumberOfStations")
                        .HasColumnType("integer");

                    b.Property<int>("PastHorizon")
                        .HasColumnType("integer");

                    b.Property<int>("PeakHorizon")
                        .HasColumnType("integer");

                    b.Property<float>("PeakThreshold")
                        .HasColumnType("real");

                    b.Property<int>("PlanningHorizon")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId")
                        .IsUnique();

                    b.ToTable("GeneralSettings");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationDeclaration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<float?>("DemandVariability")
                        .HasColumnType("real");

                    b.Property<int?>("InitialBuffer")
                        .HasColumnType("integer");

                    b.Property<float?>("LeadTime")
                        .HasColumnType("real");

                    b.Property<float?>("ProcessingTime")
                        .HasColumnType("real");

                    b.Property<int?>("StationIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId", "StationIndex");

                    b.ToTable("StationDeclarations");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationDemandForecast", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Instant")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationDeclarationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationDeclarationId", "Instant");

                    b.ToTable("StationDemandForecasts");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<float>("Percentage")
                        .HasColumnType("real");

                    b.Property<Guid>("SourceStationDeclarationId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetStationIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceStationDeclarationId", "TargetStationIndex");

                    b.ToTable("StationInputs");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationPastBuffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Instant")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationDeclarationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationDeclarationId", "Instant");

                    b.ToTable("StationPastBuffers");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationPastOrderAmount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Instant")
                        .HasColumnType("integer");

                    b.Property<Guid>("StationDeclarationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StationDeclarationId", "Instant");

                    b.ToTable("StationPastOrderAmounts");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ForecastModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FeatureCount")
                        .HasColumnType("integer");

                    b.Property<int>("ForecastHorizon")
                        .HasColumnType("integer");

                    b.Property<string>("Hyperparameters")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LookbackWindow")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ModelData")
                        .HasColumnType("bytea");

                    b.Property<int>("ModelType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float?>("TrainingAccuracy")
                        .HasColumnType("real");

                    b.Property<DateTime>("TrainingEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TrainingSampleCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TrainingStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("ValidationAccuracy")
                        .HasColumnType("real");

                    b.Property<float?>("ValidationMAE")
                        .HasColumnType("real");

                    b.Property<float>("ValidationMAPE")
                        .HasColumnType("real");

                    b.Property<float?>("ValidationRMSE")
                        .HasColumnType("real");

                    b.Property<int?>("ValidationSampleCount")
                        .HasColumnType("integer");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ConfigurationId", "IsActive");

                    b.ToTable("ForecastModels");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ForecastPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualValues")
                        .HasColumnType("jsonb");

                    b.Property<float?>("ConfidenceLevel")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ForecastModelId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ForecastStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LowerBound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LowerConfidenceInterval")
                        .HasColumnType("jsonb");

                    b.Property<float?>("MAE")
                        .HasColumnType("real");

                    b.Property<float?>("MAPE")
                        .HasColumnType("real");

                    b.Property<string>("PredictedValues")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("PredictionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StationDeclarationId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StationDeclarationId1")
                        .HasColumnType("uuid");

                    b.Property<string>("UpperBound")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UpperConfidenceInterval")
                        .HasColumnType("jsonb");

                    b.Property<bool>("WasOverridden")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasUsedInPlanning")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("PredictionDate");

                    b.HasIndex("StationDeclarationId1");

                    b.HasIndex("ForecastModelId", "PredictionDate");

                    b.HasIndex("StationDeclarationId", "ForecastStartDate");

                    b.ToTable("ForecastPredictions");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ForecastTrainingData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BufferLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("DemandValue")
                        .HasColumnType("integer");

                    b.Property<string>("ExogenousFactors")
                        .HasColumnType("text");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ObservationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OrderAmount")
                        .HasColumnType("integer");

                    b.Property<int>("Quarter")
                        .HasColumnType("integer");

                    b.Property<int>("StationDeclarationId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StationDeclarationId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ObservationDate");

                    b.HasIndex("StationDeclarationId1");

                    b.HasIndex("ConfigurationId", "ObservationDate");

                    b.HasIndex("StationDeclarationId", "ObservationDate");

                    b.ToTable("ForecastTrainingData");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ModelMetrics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalMetrics")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EvaluationEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EvaluationStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EvaluationType")
                        .HasColumnType("integer");

                    b.Property<float?>("ForecastErrorStdDev")
                        .HasColumnType("real");

                    b.Property<int?>("ForecastHorizon")
                        .HasColumnType("integer");

                    b.Property<Guid>("ForecastModelId")
                        .HasColumnType("uuid");

                    b.Property<float>("MAE")
                        .HasColumnType("real");

                    b.Property<float>("MAPE")
                        .HasColumnType("real");

                    b.Property<float?>("MeanForecastError")
                        .HasColumnType("real");

                    b.Property<float>("RMSE")
                        .HasColumnType("real");

                    b.Property<float?>("RSquared")
                        .HasColumnType("real");

                    b.Property<int>("SampleCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StationDeclarationId")
                        .HasColumnType("uuid");

                    b.Property<float?>("TrackingSignal")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("StationDeclarationId");

                    b.HasIndex("ForecastModelId", "EvaluationType");

                    b.HasIndex("ForecastModelId", "StationDeclarationId");

                    b.ToTable("ModelMetrics");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPPC.Core.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.Configuration", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.User", "User")
                        .WithMany("Configurations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.GeneralSettings", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.Configuration", "Configuration")
                        .WithOne("GeneralSettings")
                        .HasForeignKey("SmartPPC.Core.Domain.GeneralSettings", "ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationDeclaration", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.Configuration", "Configuration")
                        .WithMany("StationDeclarations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationDemandForecast", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "StationDeclaration")
                        .WithMany("DemandForecasts")
                        .HasForeignKey("StationDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationInput", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "SourceStationDeclaration")
                        .WithMany("NextStationInputs")
                        .HasForeignKey("SourceStationDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceStationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationPastBuffer", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "StationDeclaration")
                        .WithMany("PastBuffers")
                        .HasForeignKey("StationDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationPastOrderAmount", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "StationDeclaration")
                        .WithMany("PastOrderAmounts")
                        .HasForeignKey("StationDeclarationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ForecastModel", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.Configuration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ForecastPrediction", b =>
                {
                    b.HasOne("SmartPPC.Core.ML.Domain.ForecastModel", "ForecastModel")
                        .WithMany()
                        .HasForeignKey("ForecastModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "StationDeclaration")
                        .WithMany()
                        .HasForeignKey("StationDeclarationId1");

                    b.Navigation("ForecastModel");

                    b.Navigation("StationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ForecastTrainingData", b =>
                {
                    b.HasOne("SmartPPC.Core.Domain.Configuration", "Configuration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "StationDeclaration")
                        .WithMany()
                        .HasForeignKey("StationDeclarationId1");

                    b.Navigation("Configuration");

                    b.Navigation("StationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.ML.Domain.ModelMetrics", b =>
                {
                    b.HasOne("SmartPPC.Core.ML.Domain.ForecastModel", "ForecastModel")
                        .WithMany()
                        .HasForeignKey("ForecastModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartPPC.Core.Domain.StationDeclaration", "StationDeclaration")
                        .WithMany()
                        .HasForeignKey("StationDeclarationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ForecastModel");

                    b.Navigation("StationDeclaration");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.Configuration", b =>
                {
                    b.Navigation("GeneralSettings");

                    b.Navigation("StationDeclarations");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.StationDeclaration", b =>
                {
                    b.Navigation("DemandForecasts");

                    b.Navigation("NextStationInputs");

                    b.Navigation("PastBuffers");

                    b.Navigation("PastOrderAmounts");
                });

            modelBuilder.Entity("SmartPPC.Core.Domain.User", b =>
                {
                    b.Navigation("Configurations");
                });
#pragma warning restore 612, 618
        }
    }
}
