using System;

namespace SmartPPC.Core.ML.Domain;

/// <summary>
/// Represents a demand forecast prediction generated by a machine learning model.
/// Contains predicted values along with confidence intervals for a specific station.
/// </summary>
public class ForecastPrediction
{
    /// <summary>
    /// Unique identifier for this prediction.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Reference to the forecast model that generated this prediction.
    /// </summary>
    public Guid ForecastModelId { get; set; }

    /// <summary>
    /// Reference to the station this prediction is for.
    /// </summary>
    public int StationDeclarationId { get; set; }

    /// <summary>
    /// The date and time when this prediction was generated.
    /// </summary>
    public DateTime PredictionDate { get; set; }

    /// <summary>
    /// The starting date/time for which the forecast is valid.
    /// </summary>
    public DateTime ForecastStartDate { get; set; }

    /// <summary>
    /// JSON array of predicted demand values for the planning horizon.
    /// Example: "[45, 52, 48, 50, ...]" for each period in the horizon.
    /// </summary>
    public string PredictedValues { get; set; } = "[]";

    /// <summary>
    /// JSON array of upper confidence interval bounds.
    /// Same length as PredictedValues.
    /// </summary>
    public string? UpperConfidenceInterval { get; set; }

    /// <summary>
    /// JSON array of lower confidence interval bounds.
    /// Same length as PredictedValues.
    /// </summary>
    public string? LowerConfidenceInterval { get; set; }

    /// <summary>
    /// Confidence level for the intervals (e.g., 0.95 for 95% confidence).
    /// </summary>
    public float? ConfidenceLevel { get; set; }

    /// <summary>
    /// JSON array of actual demand values that occurred (populated after the fact).
    /// Used for model evaluation and performance tracking.
    /// </summary>
    public string? ActualValues { get; set; }

    /// <summary>
    /// Mean Absolute Error between predicted and actual values (calculated post-facto).
    /// </summary>
    public float? MAE { get; set; }

    /// <summary>
    /// Mean Absolute Percentage Error (calculated post-facto).
    /// </summary>
    public float? MAPE { get; set; }

    /// <summary>
    /// Whether this prediction was used in DDMRP planning.
    /// </summary>
    public bool WasUsedInPlanning { get; set; }

    /// <summary>
    /// Whether this prediction was manually overridden by a user.
    /// </summary>
    public bool WasOverridden { get; set; }

    /// <summary>
    /// Timestamp when this prediction was created.
    /// </summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>
    /// Navigation property to the forecast model.
    /// </summary>
    public ForecastModel? ForecastModel { get; set; }

    // Note: StationDeclarationId stores the station index (int), not the StationDeclaration.Id (Guid)
    // No navigation property due to type mismatch

    public string LowerBound { get; set; }
    public string UpperBound { get; set; }
}
